### ISSUE TITLE
Improve Unit Test Coverage

### ISSUE THREAD

**Issue by radicleart** [Stacks-Builders/sbtc-bridge-web#118]
The sbtc bridge unit tests have evolved through several pivots in the core functionality.

This issue requires;

1. Tests to be stabilised - all tests must be properly mocked to avoid intermittent test failures - no external http requests to be made by running the tests 
2. Svelte component test coverage - coverage of the svelte components needs to be improved to 50%
3. Typescript classes / file - coverage needs to improved to 80%

The tests need to be better organised and structured.

Note: we get test failures upgrading noble/secp256 to v2 see this [Issue](https://github.com/paulmillr/noble-secp256k1/issues/110). Ideally this issue should include a fix for this.

**Comment by igorsyl** [comment]
cc @sergey-shandar as he is owning technical leadership of Testing Infra across sBTC including UI/UX.

**Comment by radicleart** [comment]
closing as fixed by other work
