### ISSUE TITLE
Bridge support for sBTC Alpha

### ISSUE THREAD

**Issue by radicleart** [Stacks-Builders/sbtc-bridge-web#201]
Supporting the sBTC Alpha release from the bridge UI/API is complicated by the different contract structures between alpha and mini. From the bridge perspective alpha and mini are separate applications with little in common.

Two approaches  to retaining support for alpha;

1. Tag the code and create new deployment
I.e. create a release tag in the UI and API Git Hubs and then create a dedicated release for both applications on their own domains.

2. Maintain support via a feature flag
I.e. keep alpha alive within the future version.

Option 2, given the degree of difference between Mini and Alpha clarity would be equivalent to supporting two different applications in the same code base. It'll create a lot of unnecessary risk due to increased complexity, on-goingly.

Option 1 is easier to support but carries the risk of breaking in the future. E.g. I can support it short term on my infrastructure but it's likely to be be brittle and to break down the line.

**Comment by netrome** [comment]
Given the push for Mini (or the Developer Release) I think Option 1 makes most sense for us, as I see it.
