### ISSUE TITLE
Lack of integrity check on third party script import

### ISSUE THREAD

**Issue by KeewenawSTX** [Stacks-Builders/sbtc-bridge-web#92]
File: Trust-Machines/sbtc-bridge-web/src/app.html

Line: 8, <script src="https://connect.trezor.io/9/trezor-connect.js"></script>

Since we're dealing with a genuine Trezor script, I would suggest adding the "integrity" security attribute:

[integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)="file_hash" - avoids the possibility of a malicious actor modifying trezor-connect.js without anyone knowing ([why this matters](https://www.csoonline.com/article/3619065/6-most-common-types-of-software-supply-chain-attacks-explained.html)). Even if a regular update happens, this integrity check failing will ensure we keep trezor-connect.js up to date.

The SHA512 hash of the file is currently: 86150316879571d7ae841b09d00a6154896749abcb1cd2467a813a29a62c031fa653ef76f68eb6ebc5f1ce2ba39abf3cf04f24f212584d23ef3854b290afb3f8

I'd also consider implementing a CSP with script-src and object-src set to the relevant Trezor server and file.
https://owasp.org/www-community/controls/Content_Security_Policy

**Comment by radicleart** [comment]
Support for trezor/ledger is longer relevant because of op_drop.
